### ISSUE TITLE
"Meta" Achievements

### ISSUE THREAD

**Issue by Kekwel** [TobiBiotex/CDS-BOT#30]
Message de Sqweeb : 
```On donne aux admins une emot rien qu'a eu genre :🥇(emote custom)
Lorsque une personne du groupe met dans le hall des héros un jeu a 100% qui impresionne les admins
ont met l'emot 🥇   là (emote custom)
et si il fait plusieurs jeu en obtenant cette émot
au bout de 50 ( emot) on va dire 
un succès pop sur discord
disant Achievement unlock blabla blabla
```

* Exemple : "*Choix des admins*"
- [x] ne prendre en compte que les messages du #haut-fait (un salon custom a rajouter dans les config ?)
- [x] si le message est une image
  - [x] si un admin met un emoji custom en réaction (a paramétrer)
    - [x] incrémenter un compteur lié à l'user 
- [x] Faire une liste de "meta" achievements, dans la limite du faisable avec Discord
- [x] Afficher ces achievements sur le profile ?
- [x] Créer une table/entité Stats lié à un User (ou dans la même table), qui va contenir toutes ses stats (lol) : 
  Nb de réaction par admin
  Nb de groupes rejoint ?
  Autres, en fonction de la liste

------

Liste par Sqweeb et Nanaki :
### Hall héros 🏆 
- [x] _Et de 1!_ : Mettre 1 100% dans le hall des héros
- [x] _Pas mal!_ : Mettre 10 100% dans le hall des héros 
- [x] _On ne l'arrête plus_ : Mettre 50 100% dans le hall des héros 
- [x] _100 100% la classe_ : Mettre 100 100 % dans le hall des héros

### Hall zéros 💩 
- [x] _Tu ne te sens pas sale?_ : Mettre 1 100% dans le hall des zéros
- [x] _Pense à bien essuyer_ : Mettre 10 100% dans le hall des zéros
- [x] _Je suis à deux doigts de vomir_ : Mettre 50 100% dans le hall des zéros
- [x] _La honte n'est pas un problème chez toi_ : Mettre 250 100% dans le hall des zéros

### Groupes/Demandes d'aide 🤝 
- [x] _Good job_ : Participer à un event de groupe
- [x] _Tu es quelqu'un de sympa en fait_ : Participer à 25 event de groupe
- [x] _Je savais qu'on pouvait compter sur toi_ : Participer à 50 event de groupe.
- [x] _Chasseur altruiste_ : Participer à 100 events de groupe

### Shop 💰 
- [x] _Bienvenue chez les rats_ : Avoir vendu un jeu dans la boutique
- [x] _On aime le pognon?_ : Avoir vendu 10 jeux dans la boutique
- [x] _Arrondir la fin du mois_ : Vendre 25 jeu via le shop
- [x] _Picsou_ : Avoir vendu 100 jeux dans la boutique
- [x] _Qu'est ce que je vais faire de tous ces points_ : Avoir 1M de Points CDS

### Énigme ❓ (a donner manuellement)
- [ ] _Hercule poireaux_ : Avoir résolu la première énigme
- [ ] _Temperance Brennan_ : Avoir résolu la seconde énigme
- [ ] _Sherlock holmes_ : Avoir résolu l'enigme

### Nb messages 💬 
- [x] _Sois pas timide_ : Avoir posté 50 messages
- [x] _C'est passionnant_ : Avoir écrit 500 messages
- [x] _Piplette_ : Avoir écrit 2 500 messages
- [x] _Il va faire tout noir_ : Avoir écrit 10 000 messages!
- [ ] _Au moins un de nous deux te trouve pas ennuyeux_ : 100 000 messages !

### Easter egg 🥚 
- [ ] _Nanakim jung un_ : Avoir regardé le profil de Nanaki
- [ ] _1 frite une fois!_ : Avoir regardé le profil de TobiBiotex

### Event communautaire (à donner manuellement ?)
- [ ] _On est jamais seul_ : Avoir participé à un event de la communauté ( organisé par les admins )
- [ ] _Toujours aux rendez vous_ : Avoir participé à 2 events de la communauté
- [ ] _Merci d'être toujours là_ : Avoir participé à 5 évents de la communauté

### Création de groupe
- [ ] _Vous cherchez des amis?_ : Créer un groupe
- [ ] _Tu charbonnes c'est bien!_ : Créer 50 groupes
- [ ] _Ah ah ah la queuleuleu_ : Créer 100 groupes
- [ ] _Un nouveau Gourou est dans la place._ : Créer 250 groupes

### Autres
- [ ] _L'émote à la même signification que ta vie, pas ouf._ : Avoir envoyé l'émoji PasOuf
- [ ] _La Pasouferie n'est jamais finie !_ : 50 fois Pas ouf

### Guides cf https://github.com/Chasseur-de-Succes/CDS-BOT/issues/97
À définir

**Comment by Kekwel** [comment]
Liste par Sqweeb :
### Hall héros 🏆 
>### _Et de 1!_
>Mettre 1 100% dans le hall des héros
>### _Pas mal!_
>Mettre 10 100% dans le hall des héros 
>### On ne l'arrête plus
>Mettre 50 100% dans le hall des héros 
>### 100 100% la classe 
>Mettre 100 100 % dans le hall des héros
### Hall zéros 💩 
>### Tu ne te sens pas sale?
>Mettre 1 100% dans le hall des zéros
>### Je suis à deux doigts de vomir
>Mettre 50 100% dans le hall des zéros
>### La honte n'est pas un problème chez toi
>Mettre 250 100% dans le hall des zéros
### Groupes/Demandes d'aide 🤝 
>### Good job
>Participer à un event de groupe
>### Tu es quelqu'un de sympas en faite
>Participer à 25 event de groupe
>### Je savais qu'on pouvait compter sur toi
>Participer à 50 event de groupe.
### Shop 💰 
>### Bienvenue chez les rats
>Avoir vendu un jeu dans la boutique
>### On aime le pognon?
>Avoir vendu 10 jeus dans la boutique
>### Picsou
>Avoir vendu 100 jeux dans la boutique
### Énigme ❓ (a donner manuellement)
>### Hercule poireaux
>Avoir résolu la première énigme
>### Temperance Brennan
>Avoir résolu la seconde énigme
>### Sherlock holmes
>Avoir résolu l'enigme
### Nb messages 💬 
>### Sois pas timide
>Avoir posté 50 messages
>### C'est passionnant
>Avoir écrit 500 messages
>### Piplette
>Avoir écrit 2 500 messages
>### Il va faire tout noir
>Avoir écrit 10 000 messages!
### Easter egg 🥚 
>### Nanakim jung un
>Avoir regardé le profil de Nanaki 
>### 1 fritte une fois!
>Avoir regardé le profil de TobiBiotex
### Event communautaire (à donner manuellement ?)
>### On est jamais seul
>Avoir participé à un event de la communauté ( organisé par les admins)
>### Toujours aux rendez vous
>Avoir participé à 2 events de la communauté
>### Merci d'être toujours là
>Avoir participé à 5 évents de la communauté

**Comment by Kekwel** [comment]
Nouveau succès proposé par Sqweeb (et Nanaki)
### Création de groupe
> Créer un groupe: Vous cherchez des amis?
Créer 50 groupes: Tu charbonnes c'est bien!
Créer 100 groupes: Ah ah ah la queuleuleu
Créer 250 groupes: Un nouveau Gourou est dans la place.
### Autres
> Tu as utilisé l'emot Pas Ouf: L'émote à la même signification que ta vie, pas ouf. 
> 50 fois Pas ouf : La Pasouferie n'est jamais finie !
### Guides cf https://github.com/Chasseur-de-Succes/CDS-BOT/issues/97
> a definir
